apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaky-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leaky-app
  template:
    metadata:
      labels:
        app: leaky-app
    spec:
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.9
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
